import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowUpRight, Building2, BadgeCheck, Headphones, Plane, ShieldCheck, Handshake, Globe2, Landmark, Check, MessageSquareQuote } from 'lucide-react';
import { Button } from './ui/button';
import { ServiceModal } from './ServiceModal';
import type { ServiceKey } from './ServicePills';
import { WHATSAPP_URL } from '@/lib/countries';
import grid from '@/assets/destinations-grid.jpg';
const destinations = [ ['Saudi Arabia','Umrah, visit & business visas','Saudi Arabia'], ['UAE / Dubai','30-day, 60-day & express visit visas','UAE'], ['Turkey','Sticker & e-visa file preparation','Turkey'], ['Schengen / Europe','Document vetting & appointment guidance','Europe/Schengen'], ['UK & USA','Visitor & business visa preparation','UK & USA'], ['Malaysia & Thailand','Tailored tours & family packages','Malaysia & Thailand'] ];
export function PortalSections() {
 const [service,setService] = useState<{key:ServiceKey;label:string}|null>(null);
 return <><section className="trust-band">{[[BadgeCheck,'Officially registered with SECP','Private Limited Company'],[ShieldCheck,'100% transparent fees','Clear costs. No surprises.'],[Headphones,'Dedicated 24/7 support','B2B & client support desk'],[Plane,'Direct airline & hotel inventory','More choice for your journey']].map(([Icon,title,sub])=>{const I=Icon as typeof Plane;return <div key={String(title)}><I/><p><strong>{String(title)}</strong><span>{String(sub)}</span></p></div>})}</section>
 <section id="services" className="portal-section"><div className="section-heading"><div><span className="eyebrow">YOUR JOURNEY, OUR EXPERTISE</span><h2>Every detail. <em>Expertly handled.</em></h2></div><p>From your first visa to your next pilgrimage,<br/>we make the complicated feel effortless.</p></div><div className="services-grid">{[{icon:Landmark,title:'Umrah & Hajj Operations',body:'Economy & VIP packages, Makkah and Madinah hotels, private GMC & Coaster transport, and group visas.',key:'umrah'},{icon:Globe2,title:'Global Visit Visas & Consultancy',body:'Tourist and business visa files, embassy appointments and cover letters for the UK, USA, Europe and beyond.',key:'visa'},{icon:Plane,title:'International Ticketing & Group Fares',body:'Competitive airfares, labour and tour group ticketing, plus 24/7 date change and reissuance support.',key:'flight'},{icon:Handshake,title:'Corporate & B2B Services',body:'A dependable travel partner for brokers, sub-agents and corporate accounts. Access dedicated wholesale rates.',key:'b2b'}].map((s,i)=><article className="service-card" key={s.key}><div className="service-top"><s.icon/><span>0{i+1}</span></div><h3>{s.title}</h3><p>{s.body}</p>{s.key==='b2b'?<Button variant="link" asChild><Link to="/b2b">Become a partner <ArrowUpRight/></Link></Button>:<Button variant="link" onClick={()=>setService({key:s.key as ServiceKey,label:s.title})}>Explore service <ArrowUpRight/></Button>}</article>)}</div><div className="additional-services"><span>ALSO AT YOUR SERVICE</span><Button variant="link" onClick={()=>setService({key:'medical',label:'Medical Appointment Booking'})}>Gulf Medical Appointments <ArrowUpRight/></Button><Button variant="link" onClick={()=>setService({key:'hotel',label:'Hotel Booking'})}>International Hotels <ArrowUpRight/></Button><Link to="/study-in-italy">Study Abroad <ArrowUpRight size={15}/></Link></div></section>
 <section className="destinations-section" id="destinations"><div className="portal-section"><div className="section-heading"><div><span className="eyebrow">THE WORLD IS CALLING</span><h2>Where will <em>you go next?</em></h2></div><Button variant="outline" asChild><Link to="/countries">All destinations <ArrowUpRight/></Link></Button></div><div className="destinations-grid">{destinations.map(([title,desc,d],i)=><article className="destination-card" key={title}><div className={`destination-photo destination-${i}`}><img src={grid} alt={`${title} travel destination`} loading="lazy" width={1536} height={1024}/><span>0{i+1} / EXPLORE</span></div><div className="destination-info"><h3>{title}</h3><p>{desc}</p><div><small>Price & processing time on request</small><Button variant="link" asChild><a href={`${WHATSAPP_URL}?text=${encodeURIComponent(`Assalam-o-Alaikum, I would like to apply for ${d}: ${desc}. Please share current prices, processing times and requirements.`)}`} target="_blank" rel="noopener noreferrer">Apply Now <ArrowUpRight/></a></Button></div></div></article>)}</div></div></section>
 <section className="portal-section why-section"><div><span className="eyebrow">THE AL-BAHR PROMISE</span><h2>Travel with confidence.<br/><em>Not uncertainty.</em></h2><p>Real people, responsible advice and a personal commitment to your journey.</p><Button asChild><Link to="/about">Meet Al-Bahr <ArrowUpRight/></Link></Button></div><div className="promise-list">{[[Building2,'A registered company. A real commitment.','Private Limited registration under Pakistani corporate laws.'],[ShieldCheck,'Honest guidance at every step.','Expert assessment of your visa file. Final decisions always rest with the embassy.'],[Check,'No hidden costs. No guesswork.','Clear fee information before you commit to a service.']].map(([Icon,t,p])=>{const I=Icon as typeof Check;return <div key={String(t)}><I/><div><h3>{String(t)}</h3><p>{String(p)}</p></div></div>})}</div></section>
 <section className="reviews-section"><div className="portal-section"><MessageSquareQuote/><span className="eyebrow">TRAVELLER EXPERIENCES</span><h2>Your journey could be <em>the next story.</em></h2><p>Client reviews and approved-visa stories are shared only with permission.<br/>Ask our team for available references, or tell us about your experience.</p><Button variant="outline" asChild><a href={`${WHATSAPP_URL}?text=${encodeURIComponent('I would like to share my experience with Al-Bahr Travels.')}`} target="_blank" rel="noopener noreferrer">Share your experience <ArrowUpRight/></a></Button></div></section><ServiceModal service={service} onClose={()=>setService(null)}/></>;
}
